---
apiVersion: v1
kind: Pod
metadata:
  name: kuardo-limit
spec:
  containers:
    - image: gcr.io/kuar-demo/kuard-amd64:blue
      name: kuardo-limit
      resources:
        requests:
          # This request at least 50% free of a core to be free
          cpu: "500m"
          memory: "128Mi"
        limits:
          cpu: "1000m"
          memory: "256Mi"
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP          